name: web_radio_example
version: 1.0.0
publish_to: "none"
environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  analog_radio:
    path: ../
dev_dependencies:
  build_runner: ^2.1.11
  build_test: ^2.1.5
  build_web_compilers: ^3.2.3
