name: analog_radio
description: Utility for adding analog radio noise to online radio. Uses the WebAudio Api.
homepage: https://github.com/antitim/analog_radio
repository: https://github.com/antitim/analog_radio
version: 2.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
